{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clario360.fullname" $ }}-{{ $name | kebabcase }}
  labels:
    app.kubernetes.io/name: {{ $name | kebabcase }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svc.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $name | kebabcase }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
{{- end }}
