{{- if and .Values.fileService.enabled .Values.fileService.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "clario360.fullname" . }}-file-service
  namespace: {{ include "clario360.namespace" . }}
  labels:
    {{- include "clario360.componentLabels" (dict "root" . "component" "file-service") | nindent 4 }}
spec:
  minAvailable: {{ .Values.fileService.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "clario360.componentSelectorLabels" (dict "root" . "component" "file-service") | nindent 6 }}
{{- end }}
